spring:
  application:
    name: spring-oauth2-resource-server

  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:none}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  mongodb:
    uri: mongodb://${DB_MONGO_USERNAME}:${DB_MONGO_PASSWORD}@${DB_MONGO_HOST:localhost}:${DB_MONGO_PORT:27017}/${DB_MONGO_NAME:post}?authSource=admin

server:
  servlet:
    context-path: /${CONTEXT_PATH:api}
  port: ${SERVER_PORT:8080}

springdoc:
  api-docs:
    path: /${API_DOCS_PATH:docs}
  swagger-ui:
    path: /${SWAGGER_UI_PATH:swagger-ui}